### ISSUE TITLE
Tab Completion Not Working in 0.12

### ISSUE THREAD

**Issue by JBlocklove** [papis/papis#399]
* papis version (`$ papis --version` or commit number): 0.12

# how to reproduce the issue
In both `zsh` and `bash` I cannot get tab completion to work properly with `papis`. Typing `papis` and tab completing provides absolutely nothing in `zsh` (similar to issue #303 but it happens with just `papis` as well as `papis add`), and doing the same in `bash` only completes with the files in that directory, which I think is the default behavior in `bash`.

The documentation for tab completion gives a couple of scripts to make completion work, but clicking on them gives a 400 error, so I am unable to test if there is a solution for this.

I am running Arch Linux and installed `papis` through the AUR.

**Comment by alexfikl** [comment]
This should be fixed by #478. Any chance you can try that out? It would be much appreciated!

If you can't install from git, just copy pasting the completion script locally should also work.
https://github.com/alexfikl/papis/blob/fix-shell-completion/scripts/shell_completion/click/zsh/_papis

**Comment by JBlocklove** [comment]
Sorry it took me a few days to get to this. I just built your `fix-shell-completion` branch and it still doesn't seem to work for me. I also tried adding just that file to the current papis master branch and still no dice.

**Comment by alexfikl** [comment]
How did you try out the branch and the completion?

I tried this (with `zsh`) and it seemed to work:
```
python -m pip install -e . (or whatever method you used to install papis from git)
eval "$(_PAPIS_COMPLETE=<shell>_source papis)"
papis <TAB>
papis add -<TAB>
```
The `eval` line should do the trick of loading the current shell completion stuff. The script that's in the PR is just a pre-generated version of that.

**Comment by JBlocklove** [comment]
Ah, yep I had forgotten that `eval` line. It looks like I need to run that line every time I open a shell at the moment, should I just add it to my `zshrc` or is there a better way where that would be automatic?

**Comment by JBlocklove** [comment]
So it goes, I can just add that to my zshrc until it gets merged. Thanks for figuring this out!

Sadly I only use Linux so I won't be of much help with Mac or Windows. I imagine Mac should work pretty similarly, but I have no idea with Windows.

**Comment by alexfikl** [comment]
> So it goes, I can just add that to my zshrc until it gets merged. Thanks for figuring this out!

You can also copy that `_papis` file to a directory from your zsh `fpath` (check what's in there with `echo $fpath`), but otherwise, yes, that's the status at the moment.

Glad to hear it works for you now and thanks for testing and helping out! 

> Sadly I only use Linux so I won't be of much help with Mac or Windows. I imagine Mac should work pretty similarly, but I have no idea with Windows.

No worries! I'm in the same boat, haha.
