### ISSUE TITLE
Rofi GUI cannot open files if there's a space anywhere in the path name

### ISSUE THREAD

**Issue by goderich** [papis/papis#63]
If there's a space either in the file name or in any of the parent directories, the rofi GUI will fail to open the PDF with the following error when run through the terminal:

```
xdg-open: unexpected argument [part after space]
Try 'xdg-open --help' for more information.
```

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/21 (Rofi GUI open wrong file, sometimes), https://github.com/alejandrogallo/papis/issues/6 (gui --rofi crashing on delete), https://github.com/alejandrogallo/papis/issues/43 (papis-python-rofi wrong name), and https://github.com/alejandrogallo/papis/issues/39 (file-name option and adding files with incomplete metadata).

**Comment by alejandrogallo** [comment]
Hi, thanks for the issue report. Does this only happen for rofi, or also for papis open ? 
We should fix this, however beware of spaces in general .... ;)

**Comment by goderich** [comment]
Both papis open and the vim interface open files with spaces in the path name perfectly fine, so I'm pretty sure this is a rofi interface thing.

And yes, I'm aware that spaces are an issue in general :) That being said, sometimes folder names with spaces are more aesthetically pleasing and easier on the eyes, as opposed to using hyphens or underscores. I like the ability to organise my papers with papis in any way I please, and for me that means multi-word names.

**Comment by alejandrogallo** [comment]
This should be fixed now by:

7edbfa293e6868729cbfb34745a9ef2db22fba63

Maybe if you've some time to burn you can
test it ;)

**Comment by goderich** [comment]
I've just cloned the git repo and installed papis from there, but the problem persists. I'm not sure if there's anything else I should be doing, if so, please tell me. I'm assuming the commit you linked is already in the master branch. Any way I can check that my version has it?

**Comment by alejandrogallo** [comment]
Hmm that is weird, it is now tested and here I have an example
where it works:

  https://asciinema.org/a/AJlWgo3NUn663F0k99T6hMnfU

What I could imagine is that the cache is kind of confused right now,
maybe you can clear the cache

  papis --cc

and then try again, maybe the path within the cache was also having some
trouble from the last version of papis.

**Comment by alejandrogallo** [comment]
Also if you're willing, you could try the branch refactor, which is to become v.0.6
hopefully next week when enough documentation has been written about the changes

**Comment by alejandrogallo** [comment]
This should be fixed in v0.6 now.
